<?php $this->layout('layout::default', ['site' => $site, 'title' => $event->get('title'), 'description' => $event->get('description')]) ?>

<?php $eventBlock = function () use ($event) { ?>
    <?=$event->get('html')?>

    <?php if ($event->has('meetup')): ?>
        <p><a href="<?=$this->escape($event->get('meetup'))?>">RSVP on meetup.com</a></p>
    <?php endif; ?>

    <?php if ($event->has('joind.in')): ?>
        <p><a href="<?=$this->escape($event->get('joind.in'))?>">View event on joind.in</a></p>
    <?php endif; ?>
<?php } ?>

<?php if ($event->has('talks')): ?>
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <?php $eventBlock(); ?>
        </div>
        <div class="col-xs-12 col-sm-6">
            <h3>Talks</h3>

            <?php foreach ($event->get('talks') as $talk): ?>
                <hr />

                <h4><?=$this->escape($talk->get('title'))?></h4>
                <p>
                    <i>
                        By
                        <a href="/speaker/<?=$this->escape($talk->get('speaker')->getId())?>">
                            <?=$this->escape($talk->get('speaker')->get('name'))?>
                        </a>
                    </i>
                </p>

                <?=$talk->get('html')?>

                <?php if ($talk->has('joind.in')): ?>
                    <a href="<?=$this->escape($talk->get('joind.in'))?>">Leave feedback on joind.in</a>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php else: ?>
    <?php $eventBlock(); ?>
<?php endif; ?>
