<?php $this->layout('layout::default', ['title' => $title, 'description' => $description]) ?>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-8 col-lg-9">
        <?=$html?>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <h3>Upcoming Events</h3>
        <ul>
            <li>Event A</li>
            <li>Event B</li>
        </ul>

        <h3>Past Events</h3>
        <ul>
            <li>Event C</li>
            <li>Event D</li>
        </ul>
    </div>
</div>
