<?php $this->layout('layout::default', ['title' => $page->get('title'), 'description' => $page->get('description')]) ?>

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-8 col-lg-9">
        <?=$page->get('html')?>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <h3>Upcoming Events</h3>
        <ul>
            <?php foreach ($futureEvents as $id => $futureEvent): ?>
                <li>
                    <a href="/event/<?=$id?>">
                        <?=$this->e($futureEvent->get('title'))?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>

        <h3>Past Events</h3>
        <ul>
            <?php foreach ($pastEvents as $id => $pastEvent): ?>
                <li>
                    <a href="/event/<?=$id?>">
                        <?=$this->e($pastEvent->get('title'))?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
