<?php $this->layout('layout::default', [
    'site' => $site,
    'title' => 'Speaker Profile: ' . $speaker->get('name'),
    'description' => 'The speaker profile for ' . $speaker->get('name') . ' at Local User Group',
]) ?>

<?php if ($speaker->has('talks')): ?>
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <?=$speaker->get('html')?>
        </div>
        <div class="col-xs-12 col-sm-6">
            <h3>Talks</h3>

            <?php foreach ($speaker->get('talks') as $talk): ?>
                <hr />

                <h4><?=$this->escape($talk->get('title'))?></h4>
                <p>
                    <i>
                        At
                        <a href="/event/<?=$this->escape($talk->get('event')->getId())?>">
                            <?=$this->escape($talk->get('event')->get('title'))?>
                        </a>
                    </i>
                </p>

                <?=$talk->get('html')?>

                <?php if ($talk->has('joind.in')): ?>
                    <a href="<?=$this->escape($talk->get('joind.in'))?>">Leave feedback on joind.in</a>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php else: ?>
    <?=$speaker->get('html')?>
<?php endif; ?>
