<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <title><?=$this->e($title)?></title>
        <?php if (isset($description)): ?><meta name="description" content="<?=$this->e($description)?>" /><?php endif; ?>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />
    --></head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/" class="active">Home</a>
                    </li>
                    <li>
                        <a href="/code-of-conduct">Code of Conduct</a>
                    </li>
                    <li>
                        <a href="/about">About</a>
                    </li>
                </li>
            </div>
        </nav>

        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <?=$this->section('content');?>
                </div>
            </div>
        </div>

        <!-- <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    --> </body>
</html>
